Use correct hook when spawning weapons
Stromic/sAdmin-Modules pull request #6
Opened 2024-03-25 04:52 UTC by MiniHood

https://maurits.tv/data/garrysmod/wiki/wiki.garrysmod.com/index7b0a.html

2024-05-07 09:55 UTC, Stromic approved these changes
Good observation, implemented!

2024-05-07 09:59 UTC, Stromic requested changes
Before this gets merged it has to be changed so it doesn't create 2 permissions for those hooks. I will have a look at it when i have time.

2024-05-08 12:08 UTC, MiniHood commented
Just pushed it there now, the PlayerSpawnSWEP event does nothing anymore, not sure why but yeah. Anywho, I've removed it in the most recent commit.

2024-07-04 20:13 UTC, Stromic commented
Just checked and it seems like that hook is being used when you use the toolgun.

2024-07-04 20:53 UTC, MiniHood commented
Gotcha, just pushed the new commit then, just hooks them both.

2024-07-04 20:53 UTC, MiniHood commented
Ah my bad just noticed you already commit the same thing 33 minutes ago

2025-02-03 20:27 UTC, Stromic commented
Thanks for your effort and letting me know, closing this as it has been implemented.

2025-02-03 20:27 UTC, closed without merging